--- 
- name: start the conversion process 
  hosts: Linux_CentOStest
  tasks:
    - name: check the version of the os 
      command: cat /etc/redhat-release

    - name: start the conversion process
      command: convert2rhel -y
